# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-16.04
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          release_name: ${{ env.SHORT_SHA }}
          tag_name: ${{ env.SHORT_SHA }}
          draft: false
          prerelease: false

  build:
    name: Build artifacts
    needs: create_release # we need to know the upload URL
    # The type of runner that the job will run on
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # - os: ubuntu-16.04
          # - os: macos-10.15
          - os: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get CMake
        uses: lukka/get-cmake@v3.19.2

      - name: Get RandR Lib for Ubuntu
        if: matrix.config.os == 'ubuntu-16.04'
        run: sudo apt-get install xorg-dev libglu1-mesa-dev libxrandr-dev

      - name: Install vcpkg on unix-like systems
        if: matrix.config.os != 'windows-2019'
        working-directory: ./tools/vcpkg
        timeout-minutes: 10
        run: |
          ls -al
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          ./vcpkg install box2d
      
      - name: Install vcpkg on Windows
        if: matrix.config.os == 'windows-2019'
        shell: pwsh
        timeout-minutes: 10
        working-directory: .\tools\vcpkg
        run: |
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install box2d:x64-windows
      
      - name: Swith to clang++ on Ubuntu
        if: matrix.config.os == 'ubuntu-16.04'
        run: |
          sudo apt-get install clang
          sudo update-alternatives --set cc `which clang`
          sudo update-alternatives --set c++ `which clang++`
      
      - name: Build the executable
        shell: pwsh
        run: |
          mkdir ./bin
          cd ./bin
          $os="${{matrix.config.os}}"
          if ($os -like '*windows*') {
            echo "build on windows"
            cmake ..
            echo -DCMAKE_BUILD_TYPE=Release "generated project files. now build..."
            cmake --config Release --target ALL_BUILD --build .
          } else {
            echo "build on *nix"
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build . 
          }
          cmake --build . 
          ls .
          cd ..

      - name: Upload Windows release - Private
        if: matrix.config.os == 'windows-2019'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: eggs-windows-x86_64.exe
          asset_path: ./bin/Release/main.exe
          asset_content_type: application/octet-stream
      
      - name: Upload Windows release - Public
        shell: pwsh
        if: matrix.config.os == 'windows-2019'
        run: |
          git clone https://${{secrets.PAT}}@github.com/ssast-tech/thuai-egg-releases ./remote_repo
          cp ./bin/Release/main.exe ./remote_repo/eggs-windows-x86_64
          cd ./remote_repo
          git config --global user.name "panda2134"
          git config --global user.email "ljypanda@live.com"
          git add ./*
          git commit -m "Update executable of ${{ matrix.config.os }}"
          git status
          git push
          while (! $?) { git pull; git push; }   

      - name: Upload unix-like releases - Private
        if: matrix.config.os != 'windows-2019'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: eggs-${{ matrix.config.os }}-x86_64
          asset_path: ./bin/main
          asset_content_type: application/octet-stream
      - name: Upload unix-like release - Public
        if: matrix.config.os != 'windows-2019'
        shell: pwsh
        run: |
          git clone https://${{secrets.PAT}}@github.com/ssast-tech/thuai-egg-releases ./remote_repo
          cp ./bin/main ./remote_repo/eggs-${{matrix.config.os}}-x86_64
          cd ./remote_repo
          git config --global user.name "panda2134"
          git config --global user.email "ljypanda@live.com"
          git add ./*
          git commit -m "Update executable of ${{ matrix.config.os }}"
          git status
          git push
          while (! $?) { git pull; git push; }   

  update_public_repo_tag:
    name: Tag the public release
    needs: build
    runs-on: ubuntu-16.04
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Modify version file
        run: |
          git clone https://${{secrets.PAT}}@github.com/ssast-tech/thuai-egg-releases $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          echo ${{ env.SHORT_SHA }} > ./latest_version
          git config --global user.name "panda2134"
          git config --global user.email "ljypanda@live.com"
          git add ./latest_version
          git commit -m "Update version to ${{ env.SHORT_SHA }}"
          git tag -a ${{ env.SHORT_SHA }} -m "Tag ${{env.SHORT_SHA}}"
          git status
          git push --tags
      - uses: EndBug/latest-tag@latest
